# Generated by Django 4.2.7 on 2023-12-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuName', models.CharField(max_length=70, verbose_name='Student name')),
                ('stuAge', models.IntegerField(verbose_name='Student Age')),
                ('stuEmail', models.EmailField(max_length=70, verbose_name='Student Email')),
                ('stuMarks', models.IntegerField(verbose_name='Marks')),
            ],
        ),
    ]
